---
Name: kalakotra-sitespider-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'audit-report/$Token': 'Kalakotra\SiteSpider\Controllers\AuditReportController'
    'api/sitespider/cron': 'Kalakotra\SiteSpider\Controllers\CronTriggerController'
