<?php

declare(strict_types=1);

namespace Kalakotra\SiteSpider\Models;

use Kalakotra\SiteSpider\Jobs\SiteAuditCrawlJob;
use Kalakotra\SiteSpider\Models\HasAuditProjectAccess;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\DB;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\ReadonlyField;

/**
 * AuditTask — one actionable checklist item for an AuditPage.
 *
 * Auto-generated by AuditService::generateTasks() after each page crawl.
 * When all actionable tasks are resolved and at least one is marked 'done',
 * AuditPage.NeedsRecrawl is set to true for re-verification on the next crawl.
 *
 * Priority guide:
 *   high   — directly hurts ranking or UX (404, noindex, missing H1, poor CWV)
 *   medium — degrades SEO quality (missing meta, orphan, multiple H1)
 *   low    — best-practice improvements (structured data, meta too long)
 *
 * @property string $Type
 * @property string $Description
 * @property string $Status       open|done|ignored
 * @property string $Priority     high|medium|low
 * @property string $ResolvedAt
 * @property int    $AuditPageID
 */
class AuditTask extends DataObject
{
    use HasAuditProjectAccess;

    private static string $table_name    = 'KSS_AuditTask';
    private static string $singular_name = 'Audit Task';
    private static string $plural_name   = 'Audit Tasks';

    private static array $db = [
        'Type'        => "Enum('broken_link,missing_title,title_too_short,title_too_long,missing_meta,meta_too_long,missing_h1,multiple_h1,heading_order,orphan,missing_alt,slow_response,cwv_poor_lcp,cwv_poor_cls,cwv_poor_inp,cannibalization,noindex,missing_structured_data,no_viewport,redirect,low_psi_mobile,low_psi_desktop', 'broken_link')",
        'Description' => 'Text',
        'Status'      => "Enum('open,done,ignored', 'open')",
        'Priority'    => "Enum('high,medium,low', 'medium')",
        'ResolvedAt'  => 'Datetime',
    ];

    private static array $has_one = [
        'AuditPage' => AuditPage::class,
    ];

    private static array $indexes = [
        'AuditPageID' => true,
        'Status'      => true,
        'Type'        => true,
    ];

    private static array $summary_fields = [
        'TypeLabel'      => 'Issue',
        'PriorityBadge'  => 'Priority',
        'Description'    => 'Description',
        'Status'         => 'Status',
        'ResolvedAt'     => 'Resolved',
    ];

    private static string $default_sort = "FIELD(Priority,'high','medium','low'), Type ASC";

    public function getCMSFields(): FieldList
    {
        $fields = parent::getCMSFields();
        $fields->removeByName(['AuditPageID', 'Type', 'Description', 'Priority', 'Status', 'ResolvedAt']);
        $fields->addFieldsToTab('Root.Main', [
            ReadonlyField::create('Type', 'Issue'),
            ReadonlyField::create('Description', 'Description'),
            ReadonlyField::create('Priority', 'Priority'),
            DropdownField::create('Status', 'Status', [
                'open' => 'Open',
                'done' => 'Done',
                'ignored' => 'Ignored',
            ]),
            ReadonlyField::create('ResolvedAt', 'Resolved at'),
        ]);
        return $fields;
    }

    // ── Type labels ───────────────────────────────────────────────────────────

    private static array $type_labels = [
        'broken_link'             => 'Broken Link (404)',
        'missing_title'           => 'Missing Page Title',
        'title_too_short'         => 'Title Too Short',
        'title_too_long'          => 'Title Too Long',
        'missing_meta'            => 'Missing Meta Description',
        'meta_too_long'           => 'Meta Description Too Long',
        'missing_h1'              => 'Missing H1 Tag',
        'multiple_h1'             => 'Multiple H1 Tags',
        'heading_order'           => 'Heading Hierarchy Issue',
        'orphan'                  => 'Orphan Page (No Inbound Links)',
        'missing_alt'             => 'Images Missing Alt Text',
        'slow_response'           => 'Slow Server Response',
        'cwv_poor_lcp'            => 'Poor LCP (Core Web Vital)',
        'cwv_poor_cls'            => 'Poor CLS (Core Web Vital)',
        'cwv_poor_inp'            => 'Poor INP (Core Web Vital)',
        'cannibalization'         => 'Keyword Cannibalization',
        'noindex'                 => 'Page Set to NoIndex',
        'missing_structured_data' => 'No Structured Data (Schema.org)',
        'no_viewport'             => 'Missing Viewport Meta Tag',
        'redirect'                => 'Redirect Detected',
        'low_psi_mobile'          => 'Low Mobile PageSpeed Score',
        'low_psi_desktop'         => 'Low Desktop PageSpeed Score',
    ];

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    protected function onBeforeWrite(): void
    {
        parent::onBeforeWrite();

        if ($this->Status === 'done' && !$this->ResolvedAt) {
            $this->ResolvedAt = date('Y-m-d H:i:s');
        }
        if ($this->Status !== 'done') {
            $this->ResolvedAt = null;
        }
    }

    protected function onAfterWrite(): void
    {
        parent::onAfterWrite();
        $this->syncPageCounters();
    }

    protected function onAfterDelete(): void
    {
        parent::onAfterDelete();
        $this->syncPageCounters();
    }

    // ── Counter sync ──────────────────────────────────────────────────────────

    /**
     * Recompute TasksTotal / TasksDone / NeedsRecrawl on KSS_AuditPage via direct
     * SQL UPDATE to avoid triggering AuditPage::onAfterWrite() recursion.
     */
    private function syncPageCounters(): void
    {
        $pageId = (int) $this->AuditPageID;
        if (!$pageId) {
            return;
        }

        $total        = (int) AuditTask::get()->filter(['AuditPageID' => $pageId])->count();
        $done         = (int) AuditTask::get()->filter(['AuditPageID' => $pageId, 'Status' => 'done'])->count();
        $ignored      = (int) AuditTask::get()->filter(['AuditPageID' => $pageId, 'Status' => 'ignored'])->count();
        $page = AuditPage::get()->byID($pageId);
        $isCrawled = $page ? (bool) $page->IsCrawled : false;
        $wasQueued = $page ? (bool) $page->NeedsRecrawl : false;
        $needsRecrawl = ($total > 0 && $done > 0 && $done + $ignored === $total && ($isCrawled || $wasQueued)) ? 1 : 0;

        DB::query(sprintf(
            'UPDATE "KSS_AuditPage" SET "TasksTotal" = %d, "TasksDone" = %d, "NeedsRecrawl" = %d, "IsCrawled" = %d WHERE "ID" = %d',
            $total,
            $done,
            $needsRecrawl,
            $needsRecrawl ? 0 : (int) $isCrawled,
            $pageId
        ));

        if ($needsRecrawl && $page) {
            $session = AuditSession::get()->byID((int) $page->AuditSessionID);
            if ($session && $session->Status === 'completed') {
                $session->Status = 'running';
                $session->FinishedAt = null;
                $session->write();
            }
            if ($session && in_array($session->Status, ['pending', 'running'], true)) {
                SiteAuditCrawlJob::queueSession((int) $session->ID);
            }
        }
    }

    // ── Virtual getters ───────────────────────────────────────────────────────

    public function getTypeLabel(): string
    {
        return self::$type_labels[$this->Type]
            ?? ucwords(str_replace('_', ' ', $this->Type));
    }

    public function getPriorityBadge(): string
    {
        return match ($this->Priority) {
            'high'   => '🔴 High',
            'medium' => '🟡 Medium',
            'low'    => '🟢 Low',
            default  => $this->Priority,
        };
    }
}
